ac:
  garage:
    service:
      token:
        expire:
          time: 86400000
base:
  url: stg-api.cardoctor.com.vn
client:
  clientId: CarDoctor
  clientSecret: 2qazXSW@3edcVFR$5tgbNHY^7ujm<KI*9ol.?:P):))
  grant-type: password
  password: password@123
  username: god
com:
  ac:
    garage:
      service:
        ignore: /v3/api-docs/**,/swagger-ui/**,/swagger-ui.html,/login,/signup
default:
  password: cardoctor@2023
file:
  libreOfficePath: Users/khanhpd2002/Desktop/CarDoctor-AC/Volumes/DATA/mFunction/data/upload
  tempExportExcel: Users/khanhpd2002/Desktop/CarDoctor-AC/Volumes/DATA/mFunction/data/upload
  uploadDir: Users/khanhpd2002/Desktop/CarDoctor-AC/Volumes/DATA/mFunction/data/upload
  url: https://stg-api.cardoctor.com.vn/cms/files/
group:
  employee:
    id: 1bd8661d-b8c7-4834-97b1-7e9d6b739b45
  garage:
    id: c0486bc3-0ffc-45d9-bc95-b168e4a9e5ad
grpc:
  client:
    grpc-test:
      address: localhost
      port: 9090
  server:
    port: 9091
kc:
  admin:
    realms: https://keycloak-dev.aggregatoricapaci.com/realms/CARDOCTOR/protocol/openid-connect/token
    users: https://keycloak-dev.aggregatoricapaci.com/admin/realms/CARDOCTOR/users
  logout: https://keycloak-dev.aggregatoricapaci.com/auth/realms/CARDOCTOR/protocol/openid-connect/logout
  user-info-uri: https://keycloak-dev.aggregatoricapaci.com/auth/realms/CARDOCTOR/protocol/openid-connect/userinfo
keycloak:
  auth-server-url: https://keycloak-dev.aggregatoricapaci.com
  bearer-only: true
  credentials:
    secret: jURZpA06pTcLKpUOrA3pY7awuluuxgEe
  realm: CARDOCTOR
  resource: cardoctor-admin
  ssl-required: external
  use-resource-role-mappings: true
my-keycloak:
  grant-type: password
logging:
  level:
    root: info
    web: debug
notification:
  driver:
    password: )%QybD8c6MTh
    username: cardoctor_driver
  garage:
    password: X#Xh6zS5)9Mt
    username: cardoctor_gara
  email:
    username: ac_email
    password: P_ldb6_Id7+_
  service:
    url: https://acx-dev.aggregatoricapaci.com/omni-channel/api/v1
server:
  port: 6559
  servlet:
    context-path: /garage-service/api/v1
single:
  cms:
    domain:
      'on':
        url: https://stg-api.cardoctor.com.vn
  sso:
    domain:
      'on':
        url: https://stg-sso-api.cardoctor.com.vn/oauth/token
spring:
  application:
    name: garage-service
  cloud:
    config:
      uri: ${CONFIG_SERVER}
  config:
    import: "optional:configserver:"
  datasource:
    url: jdbc:mysql://10.10.10.9:3306/cardoctor_gms_garage
    username: root
    password: ac@2023
    hikari:
      connectionTimeout: 30000
      idleTimeout: 30000
      maxLifetime: 2000000
      maximumPoolSize: 10
      minimumIdle: 5
  jpa:
    show-sql: true
  devtools:
    add-properties: false
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
springdoc:
  swagger-ui:
    operationsSorter: method
    path: /swagger-ui.html
system:
  error:
    log-content: Thông báo sự cố GMS Gara Dev
    send-to: khanh.pd2002@gmail.com
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health","prometheus", "metrics" ]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
      tags:
        application: ${spring.application.name}
    prometheus:
      enabled: true